
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("9a5a0f87-f5ba-465f-a5ed-18bb62cf066a")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class DojoTrackDBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new DojoTrackDBEntities object using the connection string found in the 'DojoTrackDBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=DojoTrackDBEntities", "DojoTrackDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new DojoTrackDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "DojoTrackDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new DojoTrackDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "DojoTrackDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Settings() As ObjectSet(Of Setting)
        Get
            If (_Settings Is Nothing) Then
                _Settings = MyBase.CreateObjectSet(Of Setting)("Settings")
            End If
            Return _Settings
        End Get
    End Property

    Private _Settings As ObjectSet(Of Setting)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Students() As ObjectSet(Of Student)
        Get
            If (_Students Is Nothing) Then
                _Students = MyBase.CreateObjectSet(Of Student)("Students")
            End If
            Return _Students
        End Get
    End Property

    Private _Students As ObjectSet(Of Student)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSettings(ByVal setting As Setting)
        MyBase.AddObject("Settings", setting)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToStudents(ByVal student As Student)
        MyBase.AddObject("Students", student)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DojoTrackDBModel", Name:="Setting")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Setting
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Setting object.
    ''' </summary>
    ''' <param name="settingId">Initial value of the SettingId property.</param>
    ''' <param name="adultHrValue">Initial value of the AdultHrValue property.</param>
    ''' <param name="kidHrValue">Initial value of the KidHrValue property.</param>
    Public Shared Function CreateSetting(settingId As Global.System.String, adultHrValue As Global.System.Double, kidHrValue As Global.System.Double) As Setting
        Dim setting as Setting = New Setting
        setting.SettingId = settingId
        setting.AdultHrValue = adultHrValue
        setting.KidHrValue = kidHrValue
        Return setting
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SettingId() As Global.System.String
        Get
            Return _SettingId
        End Get
        Set
            If (_SettingId <> Value) Then
                OnSettingIdChanging(value)
                ReportPropertyChanging("SettingId")
                _SettingId = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("SettingId")
                OnSettingIdChanged()
            End If
        End Set
    End Property

    Private _SettingId As Global.System.String
    Private Partial Sub OnSettingIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSettingIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AdultHrValue() As Global.System.Double
        Get
            Return _AdultHrValue
        End Get
        Set
            OnAdultHrValueChanging(value)
            ReportPropertyChanging("AdultHrValue")
            _AdultHrValue = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AdultHrValue")
            OnAdultHrValueChanged()
        End Set
    End Property

    Private _AdultHrValue As Global.System.Double
    Private Partial Sub OnAdultHrValueChanging(value As Global.System.Double)
    End Sub

    Private Partial Sub OnAdultHrValueChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property KidHrValue() As Global.System.Double
        Get
            Return _KidHrValue
        End Get
        Set
            OnKidHrValueChanging(value)
            ReportPropertyChanging("KidHrValue")
            _KidHrValue = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("KidHrValue")
            OnKidHrValueChanged()
        End Set
    End Property

    Private _KidHrValue As Global.System.Double
    Private Partial Sub OnKidHrValueChanging(value As Global.System.Double)
    End Sub

    Private Partial Sub OnKidHrValueChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DojoTrackDBModel", Name:="Student")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Student
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Student object.
    ''' </summary>
    ''' <param name="studentId">Initial value of the StudentId property.</param>
    ''' <param name="fname">Initial value of the Fname property.</param>
    ''' <param name="lname">Initial value of the Lname property.</param>
    ''' <param name="phone">Initial value of the Phone property.</param>
    ''' <param name="active">Initial value of the Active property.</param>
    ''' <param name="teacher">Initial value of the Teacher property.</param>
    ''' <param name="admin">Initial value of the Admin property.</param>
    ''' <param name="hoursEarned">Initial value of the HoursEarned property.</param>
    ''' <param name="hoursTaught">Initial value of the HoursTaught property.</param>
    ''' <param name="rank">Initial value of the Rank property.</param>
    ''' <param name="startDate">Initial value of the StartDate property.</param>
    ''' <param name="adult">Initial value of the Adult property.</param>
    ''' <param name="loginName">Initial value of the LoginName property.</param>
    ''' <param name="loginPw">Initial value of the LoginPw property.</param>
    Public Shared Function CreateStudent(studentId As Global.System.Guid, fname As Global.System.String, lname As Global.System.String, phone As Global.System.String, active As Global.System.Boolean, teacher As Global.System.Boolean, admin As Global.System.Boolean, hoursEarned As Global.System.Double, hoursTaught As Global.System.Int32, rank As Global.System.String, startDate As Global.System.DateTime, adult As Global.System.Boolean, loginName As Global.System.String, loginPw As Global.System.String) As Student
        Dim student as Student = New Student
        student.StudentId = studentId
        student.Fname = fname
        student.Lname = lname
        student.Phone = phone
        student.Active = active
        student.Teacher = teacher
        student.Admin = admin
        student.HoursEarned = hoursEarned
        student.HoursTaught = hoursTaught
        student.Rank = rank
        student.StartDate = startDate
        student.Adult = adult
        student.LoginName = loginName
        student.LoginPw = loginPw
        Return student
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StudentId() As Global.System.Guid
        Get
            Return _StudentId
        End Get
        Set
            If (_StudentId <> Value) Then
                OnStudentIdChanging(value)
                ReportPropertyChanging("StudentId")
                _StudentId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("StudentId")
                OnStudentIdChanged()
            End If
        End Set
    End Property

    Private _StudentId As Global.System.Guid
    Private Partial Sub OnStudentIdChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnStudentIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Fname() As Global.System.String
        Get
            Return _Fname
        End Get
        Set
            OnFnameChanging(value)
            ReportPropertyChanging("Fname")
            _Fname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Fname")
            OnFnameChanged()
        End Set
    End Property

    Private _Fname As Global.System.String
    Private Partial Sub OnFnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Lname() As Global.System.String
        Get
            Return _Lname
        End Get
        Set
            OnLnameChanging(value)
            ReportPropertyChanging("Lname")
            _Lname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Lname")
            OnLnameChanged()
        End Set
    End Property

    Private _Lname As Global.System.String
    Private Partial Sub OnLnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Phone() As Global.System.String
        Get
            Return _Phone
        End Get
        Set
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property

    Private _Phone As Global.System.String
    Private Partial Sub OnPhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Active() As Global.System.Boolean
        Get
            Return _Active
        End Get
        Set
            OnActiveChanging(value)
            ReportPropertyChanging("Active")
            _Active = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Active")
            OnActiveChanged()
        End Set
    End Property

    Private _Active As Global.System.Boolean
    Private Partial Sub OnActiveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnActiveChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Teacher() As Global.System.Boolean
        Get
            Return _Teacher
        End Get
        Set
            OnTeacherChanging(value)
            ReportPropertyChanging("Teacher")
            _Teacher = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Teacher")
            OnTeacherChanged()
        End Set
    End Property

    Private _Teacher As Global.System.Boolean
    Private Partial Sub OnTeacherChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnTeacherChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Admin() As Global.System.Boolean
        Get
            Return _Admin
        End Get
        Set
            OnAdminChanging(value)
            ReportPropertyChanging("Admin")
            _Admin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Admin")
            OnAdminChanged()
        End Set
    End Property

    Private _Admin As Global.System.Boolean
    Private Partial Sub OnAdminChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnAdminChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property HoursEarned() As Global.System.Double
        Get
            Return _HoursEarned
        End Get
        Set
            OnHoursEarnedChanging(value)
            ReportPropertyChanging("HoursEarned")
            _HoursEarned = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("HoursEarned")
            OnHoursEarnedChanged()
        End Set
    End Property

    Private _HoursEarned As Global.System.Double
    Private Partial Sub OnHoursEarnedChanging(value As Global.System.Double)
    End Sub

    Private Partial Sub OnHoursEarnedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property HoursTaught() As Global.System.Int32
        Get
            Return _HoursTaught
        End Get
        Set
            OnHoursTaughtChanging(value)
            ReportPropertyChanging("HoursTaught")
            _HoursTaught = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("HoursTaught")
            OnHoursTaughtChanged()
        End Set
    End Property

    Private _HoursTaught As Global.System.Int32
    Private Partial Sub OnHoursTaughtChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnHoursTaughtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Rank() As Global.System.String
        Get
            Return _Rank
        End Get
        Set
            OnRankChanging(value)
            ReportPropertyChanging("Rank")
            _Rank = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Rank")
            OnRankChanged()
        End Set
    End Property

    Private _Rank As Global.System.String
    Private Partial Sub OnRankChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRankChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StartDate() As Global.System.DateTime
        Get
            Return _StartDate
        End Get
        Set
            OnStartDateChanging(value)
            ReportPropertyChanging("StartDate")
            _StartDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("StartDate")
            OnStartDateChanged()
        End Set
    End Property

    Private _StartDate As Global.System.DateTime
    Private Partial Sub OnStartDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnStartDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Adult() As Global.System.Boolean
        Get
            Return _Adult
        End Get
        Set
            OnAdultChanging(value)
            ReportPropertyChanging("Adult")
            _Adult = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Adult")
            OnAdultChanged()
        End Set
    End Property

    Private _Adult As Global.System.Boolean
    Private Partial Sub OnAdultChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnAdultChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LoginName() As Global.System.String
        Get
            Return _LoginName
        End Get
        Set
            OnLoginNameChanging(value)
            ReportPropertyChanging("LoginName")
            _LoginName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LoginName")
            OnLoginNameChanged()
        End Set
    End Property

    Private _LoginName As Global.System.String
    Private Partial Sub OnLoginNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLoginNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LoginPw() As Global.System.String
        Get
            Return _LoginPw
        End Get
        Set
            OnLoginPwChanging(value)
            ReportPropertyChanging("LoginPw")
            _LoginPw = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LoginPw")
            OnLoginPwChanged()
        End Set
    End Property

    Private _LoginPw As Global.System.String
    Private Partial Sub OnLoginPwChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLoginPwChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Paid() As Nullable(Of Global.System.Boolean)
        Get
            Return _Paid
        End Get
        Set
            OnPaidChanging(value)
            ReportPropertyChanging("Paid")
            _Paid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Paid")
            OnPaidChanged()
        End Set
    End Property

    Private _Paid As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnPaidChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnPaidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastLogin() As Nullable(Of Global.System.DateTime)
        Get
            Return _LastLogin
        End Get
        Set
            OnLastLoginChanging(value)
            ReportPropertyChanging("LastLogin")
            _LastLogin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastLogin")
            OnLastLoginChanged()
        End Set
    End Property

    Private _LastLogin As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLastLoginChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLastLoginChanged()
    End Sub

    #End Region
End Class

#End Region

